### ISSUE TITLE
Java driver roadmap to production ready usage

### ISSUE THREAD

**Issue by innopreneur** [bigchaindb/java-driver#3]
**This is a drafted roadmap or things-to-do for this repo, to make it ready to be used in applications to connect to bigchaindb network.**

- [x] Fork crypto-conditions lib - https://github.com/bakaoh/android-crypto-conditions under bigchaindb repo - https://github.com/bigchaindb/java-crypto-conditions.
- [x] Update [java-crypto-conditions](https://github.com/bigchaindb/java-crypto-conditions)( README
- [x] Rebrand [java-crypto-conditions](https://github.com/bigchaindb/java-crypto-conditions) source code to bigchaindb
- [x] Publish [java-crypto-conditions](https://github.com/bigchaindb/java-crypto-conditions) jar in maven repo (refer [guidelines](https://maven.apache.org/repository/guide-central-repository-upload.html)) 
- [x] Rebrand java-driver (this repo) source code to bigchaindb
- [x] Update Java driver README for updated usage instructions
- [x] Publish java-driver jar to maven.(refer [guidelines](https://maven.apache.org/repository/guide-central-repository-upload.html))
- [x] Set-up Travis integration with java-driver (refer [guildelines](https://docs.travis-ci.com/user/getting-started/))
- [x] Update the link to the Java driver in the bigchaindb.com web page, and move it from under **Community Drivers** to under **Official Drivers** https://github.com/bigchaindb/site/blob/master/_src/_data/drivers.yml
- [x] Update the link to the Java driver in the BigchainDB Server docs page, and it move it under **Libraries and Tools Maintained by the BigchainDB Team** https://github.com/bigchaindb/bigchaindb/blob/master/docs/server/source/drivers-clients/index.rst

**Comment by ttmc** [comment]
All of this issue's tasks have been checked off as done, so I'm closing it.
